//! Pull request creation and auto-merge using Forgejo/Gitea API
//!
//! This module provides functions to create and auto-merge pull requests
//! on Forgejo/Gitea instances using direct HTTP requests. The URL parser
//! is generic and works with any git host (HTTPS, SSH shorthand, SSH URL).

use super::WorkspaceError;
use serde::{Deserialize, Serialize};

/// Parsed git remote URL components
#[derive(Debug)]
pub struct GitRemote {
    pub host: String,
    pub owner: String,
    pub repo: String,
}

/// Parse a git URL into (host, owner, repo) components
///
/// Supports HTTPS, SSH shorthand, and SSH URL formats for any host:
/// - `https://git.example.com/owner/repo[.git]`
/// - `git@git.example.com:owner/repo[.git]`
/// - `ssh://git@git.example.com[:port]/owner/repo[.git]`
pub fn parse_git_url(url: &str) -> Result<GitRemote, WorkspaceError> {
    let url = url.trim_end_matches(".git");

    // HTTPS/HTTP: https://host/owner/repo
    for prefix in &["https://", "http://"] {
        if let Some(rest) = url.strip_prefix(prefix) {
            let parts: Vec<&str> = rest.splitn(4, '/').collect();
            if parts.len() >= 3
                && !parts[0].is_empty()
                && !parts[1].is_empty()
                && !parts[2].is_empty()
            {
                return Ok(GitRemote {
                    host: parts[0].to_string(),
                    owner: parts[1].to_string(),
                    repo: parts[2].to_string(),
                });
            }
        }
    }

    // SSH shorthand: git@host:owner/repo (colon separates host from path)
    if let Some(rest) = url.strip_prefix("git@") {
        if let Some((host, path)) = rest.split_once(':') {
            let parts: Vec<&str> = path.splitn(3, '/').collect();
            if parts.len() >= 2 && !host.is_empty() && !parts[0].is_empty() && !parts[1].is_empty()
            {
                return Ok(GitRemote {
                    host: host.to_string(),
                    owner: parts[0].to_string(),
                    repo: parts[1].to_string(),
                });
            }
        }
    }

    // SSH URL: ssh://[user@]host[:port]/owner/repo
    if let Some(rest) = url.strip_prefix("ssh://") {
        let rest = rest.split_once('@').map_or(rest, |(_, after)| after);
        if let Some((host_port, path)) = rest.split_once('/') {
            // Strip port if present: "host:2222" -> "host"
            let host = host_port.split(':').next().unwrap_or(host_port);
            let parts: Vec<&str> = path.splitn(3, '/').collect();
            if parts.len() >= 2 && !host.is_empty() && !parts[0].is_empty() && !parts[1].is_empty()
            {
                return Ok(GitRemote {
                    host: host.to_string(),
                    owner: parts[0].to_string(),
                    repo: parts[1].to_string(),
                });
            }
        }
    }

    Err(WorkspaceError::InvalidPath(format!(
        "could not parse git URL: {}",
        url
    )))
}

#[derive(Serialize)]
struct CreatePullRequest {
    title: String,
    head: String,
    base: String,
    body: String,
}

#[derive(Deserialize)]
struct PullRequestResponse {
    number: u64,
    html_url: String,
}

#[derive(Serialize)]
struct MergePullRequest {
    /// Merge method: merge, rebase, rebase-merge, squash, fast-forward-only
    #[serde(rename = "Do")]
    method: String,
    delete_branch_after_merge: bool,
    merge_when_checks_succeed: bool,
}

/// Create a pull request on a Forgejo/Gitea instance
///
/// # Arguments
/// * `repo_url` - Git repository URL (any format — host/owner/repo are extracted)
/// * `head_branch` - Source branch for the PR (e.g., "job-01HXABC...")
/// * `base_branch` - Target branch for the PR (e.g., "main")
/// * `commits` - List of commit messages to include in PR body
/// * `auth_header_value` - Formatted authorization header value (e.g., "token abc123")
///
/// # Returns
/// A tuple of (PR number, HTML URL)
pub async fn create_pull_request(
    repo_url: &str,
    head_branch: &str,
    base_branch: &str,
    commits: &[String],
    auth_header_value: &str,
) -> Result<(u64, String), WorkspaceError> {
    let remote = parse_git_url(repo_url)?;

    tracing::info!(
        host = %remote.host,
        owner = %remote.owner,
        repo = %remote.repo,
        head = %head_branch,
        base = %base_branch,
        "creating pull request"
    );

    let title = if commits.is_empty() {
        "Auto-PR: Changes from nix-jail".to_string()
    } else {
        format!("Auto-PR: {}", commits[0])
    };

    let commit_list = if commits.is_empty() {
        "No commit messages available".to_string()
    } else {
        commits
            .iter()
            .map(|c| format!("- {}", c))
            .collect::<Vec<_>>()
            .join("\n")
    };

    let body = format!("## Commits\n{}\n\n---\nGenerated by nix-jail", commit_list);

    let request_body = CreatePullRequest {
        title,
        head: head_branch.to_string(),
        base: base_branch.to_string(),
        body,
    };

    let client = reqwest::Client::new();
    let response = client
        .post(format!(
            "https://{}/api/v1/repos/{}/{}/pulls",
            remote.host, remote.owner, remote.repo
        ))
        .header("Authorization", auth_header_value)
        .header("Accept", "application/json")
        .header("Content-Type", "application/json")
        .json(&request_body)
        .send()
        .await
        .map_err(|e| {
            WorkspaceError::IoError(std::io::Error::other(format!(
                "failed to send pull request: {}",
                e
            )))
        })?;

    if !response.status().is_success() {
        let status = response.status();
        let body = response.text().await.unwrap_or_default();
        return Err(WorkspaceError::IoError(std::io::Error::other(format!(
            "Forgejo API error {}: {}",
            status, body
        ))));
    }

    let pr: PullRequestResponse = response.json().await.map_err(|e| {
        WorkspaceError::IoError(std::io::Error::other(format!(
            "failed to parse pull request response: {}",
            e
        )))
    })?;

    tracing::info!(pr_url = %pr.html_url, pr_number = pr.number, "pull request created");
    Ok((pr.number, pr.html_url))
}

/// Request auto-merge for a pull request on a Forgejo/Gitea instance
///
/// If branch protection rules require CI, Forgejo queues this as a scheduled
/// auto-merge. Without protection rules, it merges immediately.
///
/// Errors are logged but not propagated — a failed merge attempt does not
/// invalidate the PR itself.
pub async fn auto_merge_pull_request(
    repo_url: &str,
    pr_number: u64,
    auth_header_value: &str,
) -> Result<(), WorkspaceError> {
    let remote = parse_git_url(repo_url)?;

    tracing::info!(
        host = %remote.host,
        owner = %remote.owner,
        repo = %remote.repo,
        pr_number = pr_number,
        "requesting auto-merge"
    );

    let request_body = MergePullRequest {
        method: "merge".to_string(),
        delete_branch_after_merge: true,
        merge_when_checks_succeed: true,
    };

    let client = reqwest::Client::new();
    let response = client
        .post(format!(
            "https://{}/api/v1/repos/{}/{}/pulls/{}/merge",
            remote.host, remote.owner, remote.repo, pr_number
        ))
        .header("Authorization", auth_header_value)
        .header("Accept", "application/json")
        .header("Content-Type", "application/json")
        .json(&request_body)
        .send()
        .await
        .map_err(|e| {
            WorkspaceError::IoError(std::io::Error::other(format!(
                "failed to send merge request: {}",
                e
            )))
        })?;

    let status = response.status();
    if status.is_success() {
        tracing::info!(pr_number = pr_number, "pull request merged");
    } else if status.as_u16() == 405 {
        // 405 = merge not allowed yet (branch protection, checks pending).
        // merge_when_checks_succeed should queue it for later.
        tracing::info!(
            pr_number = pr_number,
            "merge queued (checks pending or branch protection active)"
        );
    } else {
        let body = response.text().await.unwrap_or_default();
        tracing::warn!(
            pr_number = pr_number,
            status = %status,
            body = %body,
            "auto-merge request failed"
        );
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_https() {
        let r = parse_git_url("https://git.example.com/example-org/example-repo").unwrap();
        assert_eq!(r.host, "git.example.com");
        assert_eq!(r.owner, "example-org");
        assert_eq!(r.repo, "example-repo");
    }

    #[test]
    fn test_parse_https_with_git_suffix() {
        let r = parse_git_url("https://git.example.com/example-org/example-repo.git").unwrap();
        assert_eq!(r.host, "git.example.com");
        assert_eq!(r.owner, "example-org");
        assert_eq!(r.repo, "example-repo");
    }

    #[test]
    fn test_parse_ssh_shorthand() {
        let r = parse_git_url("git@git.example.com:example-org/example-repo").unwrap();
        assert_eq!(r.host, "git.example.com");
        assert_eq!(r.owner, "example-org");
        assert_eq!(r.repo, "example-repo");
    }

    #[test]
    fn test_parse_ssh_shorthand_with_git_suffix() {
        let r = parse_git_url("git@git.example.com:example-org/example-repo.git").unwrap();
        assert_eq!(r.host, "git.example.com");
        assert_eq!(r.owner, "example-org");
        assert_eq!(r.repo, "example-repo");
    }

    #[test]
    fn test_parse_ssh_url_with_port() {
        let r = parse_git_url("ssh://git@git.example.com:2222/example-org/example-repo").unwrap();
        assert_eq!(r.host, "git.example.com");
        assert_eq!(r.owner, "example-org");
        assert_eq!(r.repo, "example-repo");
    }

    #[test]
    fn test_parse_ssh_url_without_port() {
        let r = parse_git_url("ssh://git@git.example.com/example-org/example-repo").unwrap();
        assert_eq!(r.host, "git.example.com");
        assert_eq!(r.owner, "example-org");
        assert_eq!(r.repo, "example-repo");
    }

    #[test]
    fn test_parse_github_https() {
        let r = parse_git_url("https://github.com/thepwagner/nix-jail").unwrap();
        assert_eq!(r.host, "github.com");
        assert_eq!(r.owner, "thepwagner");
        assert_eq!(r.repo, "nix-jail");
    }

    #[test]
    fn test_parse_github_ssh() {
        let r = parse_git_url("git@github.com:thepwagner/nix-jail").unwrap();
        assert_eq!(r.host, "github.com");
        assert_eq!(r.owner, "thepwagner");
        assert_eq!(r.repo, "nix-jail");
    }

    #[test]
    fn test_parse_invalid_url() {
        assert!(parse_git_url("not-a-url").is_err());
    }

    #[test]
    fn test_parse_http() {
        let r = parse_git_url("http://gitea.local/org/repo").unwrap();
        assert_eq!(r.host, "gitea.local");
        assert_eq!(r.owner, "org");
        assert_eq!(r.repo, "repo");
    }
}
